### ISSUE TITLE
Fr: Bad Ceiling beam Description

### ISSUE THREAD

**Issue by tfchdj** [bartwe/StaxelTranslations#1139]
The description of Ceiling beam indicate them as being light source, which they aren't.
![image](https://user-images.githubusercontent.com/57014389/115284282-c46d0e80-a14c-11eb-9447-9bfdf22708d6.png)

**Comment by bartwe** [comment]
Could you please edit the relevant file here https://github.com/bartwe/StaxelTranslations/tree/main/fr-FR and create a Pull Request with the fix ?
